// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AggregateData struct {
	Name  string `json:"name"`
	Count int    `json:"count"`
}

type HeatmapData struct {
	NetworkType string  `json:"networkType"`
	ClientType  string  `json:"clientType"`
	SyncStatus  string  `json:"syncStatus"`
	Latitude    float64 `json:"latitude"`
	Longitude   float64 `json:"longitude"`
}
