// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AggregateData struct {
	Name  string `json:"name"`
	Count int    `json:"count"`
}

type Node struct {
	ID            string  `json:"id"`
	IP4           *string `json:"ip4"`
	IP6           *string `json:"ip6"`
	TCPPort       *int    `json:"tcpPort"`
	UDPPort       *int    `json:"udpPort"`
	Attnets       *string `json:"attnets"`
	Eth2          string  `json:"eth2"`
	Enode         string  `json:"enode"`
	AgentName     string  `json:"agentName"`
	AgentVersion  string  `json:"agentVersion"`
	Country       *string `json:"country"`
	City          *string `json:"city"`
	Isp           *string `json:"isp"`
	IsConnectable bool    `json:"isConnectable"`
	LastConnected *int    `json:"lastConnected"`
}
