name: ---Nodewatch API PROD Build and Deploy---
#Should be triggered after linting workflow is successful and the release tag contains "prod"
#HINT: Linting should be triggered by release 
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
on:
  release:
    types: [released]
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

env:
  AWS_REGION: "us-east-2"
  ENV: prod
  ECS_CLUSTER: "nodewatch-prod-cluster"

jobs:
  nodewatch-api-image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: "arn:aws:iam::246308468282:role/github-actions-prod-role"
          aws-region: "us-east-2"
          role-session-name: GithubAction
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Image Build
        id: image-build
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: "kong-prod-ecr"
          ENV: "prod"
          KONG_IMAGE_TAG: 2.5.0-alpine
        run: |
          docker pull kong:$KONG_IMAGE_TAG
          docker tag kong:$KONG_IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:kong.$KONG_IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:kong.$KONG_IMAGE_TAG
  user-image-build:
    uses: ChainSafe/files-api/.github/workflows/template_build_prod.yml@dev
    with:
      ASSUME_ROLE: "arn:aws:iam::246308468282:role/github-actions-prod-role"
      AWS_REGION: "us-east-2"
      ECR_REPOSITORY: "user-prod-ecr"
      DOCKERFILE_PATH: "user/Dockerfile"
      IMAGE_TAG: ${{ github.ref_name }}
      ENV: "prod"
  
  deploy-services:
    uses: ChainSafe/files-api/.github/workflows/template_deploy_prod.yml@dev
    needs: [kong-image-build,user-image-build, search-image-build, pinning-image-build, billing-image-build, files-image-build, filesmigration-image-build, billingmigration-image-build, usermigration-image-build]
    if: "!failure() && !cancelled()"
    with:
      ASSUME_ROLE: "arn:aws:iam::246308468282:role/github-actions-prod-role"
      AWS_REGION: "us-east-2"
      ECS_CLUSTER: "storage-prod-cluster"
      IMAGE_TAG: ${{ github.ref_name }}
      ENV: "prod"