# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

name: Build & Deploy to AWS

on:
  push:
    branches:
      - 'fix/ci'

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ECR_REPO: ${{ secrets.AWS_ECR_REPO }}
  ENVIRONMENT: PROD
  
jobs:
  build:
    name: build_deploy_prod
    runs-on: ubuntu-latest

    steps:
      # download the source code into the runner
      - name: checkout
        uses: actions/checkout@v2

      - name: short sha
        id: vars
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-actions-role
          region: ${{ env.AWS_REGION }}
          
      # gather metadata from git & github actions to reference in docker
      - name: git & github metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.AWS_ECR_REPO }}

      # login in docker repository
      - name: docker login
        uses: aws-actions/amazon-ecr-login@v1

      # build a docker image
      - name: docker & push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.AWS_ECR_REPO }}:latest
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.AWS_ECR_REPO }}:${{ steps.vars.outputs.sha }}
      
      # deploy to AWS ECS
      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: infra/aws-ecs/task_definition_${{ env.ENVIRONMENT }}.json
          service: nodewatch-${{ env.ENVIRONMENT }}-service
          cluster: nodewatch-${{ env.ENVIRONMENT }}-cluster
          wait-for-service-stability: true
