# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

name: Deploy ECS Prod

on:
  push:
    tags:
      - v*

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }
  ECR_REPO: ${{ secrets.AWS_ECR_REPO }}
  ENVIRONMENT: PROD

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v2
      - run: sleep 5
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-actions-${{ env.ENVIRONMENT }}-nodewatch
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GithubActions

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs/task_definition_${{ env.ENVIRONMENT }}.json
          service: nodewatch-${{ env.ENVIRONMENT }}-service
          cluster: nodewatch-${{ env.ENVIRONMENT }}-cluster
          wait-for-service-stability: true